name: Security Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 1. SAST - Bandit
      - name: Run Bandit (SAST)
        run: |
          bandit -r . -f txt -o bandit_report.txt || true
          cat bandit_report.txt

      # 2. Поднимаем Flask
      - name: Run Flask App
        run: |
          python app.py &
          sleep 5

      # 3. DAST - OWASP ZAP
      - name: Run OWASP ZAP (DAST)
        run: |
          docker run --net=host -v $(pwd):/zap/wrk/:rw -t zaproxy/zap-stable zap-baseline.py -t http://127.0.0.1:5000/api/users -r zap-report.html || true

      # 4. Сохранение всех отчетов в Артефакты
      - name: Upload Security Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit_report.txt
            zap-report.html
